import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `bun run cf:typegen` (wrangler). Regenerated wholesale, so
    // hand-fixing lint findings in it would just be undone on the next run.
    "cloudflare-env.d.ts",
    // OpenNext / wrangler build output (`bun run cf:build`). worker.ts at the repo
    // root imports .open-next/worker.js, and without this eslint would crawl the
    // whole generated server bundle.
    ".open-next/**",
    ".wrangler/**",
  ]),
]);

export default eslintConfig;
