// Passive sync only — this file is generated by `pnpm db:pull` (drizzle-kit pull),
// which introspects the schema your DBA designs in the Neon database.
// Do NOT hand-author tables here; we never push schema from this app.
// Until the DBA creates tables, this stays empty.
export {};
